"""Write ``AGENTS.md`` — the cross-tool agent instructions for the project.

AGENTS.md is the open convention every major coding agent reads (Claude Code,
Codex, Cursor, Copilot, Gemini CLI, …): a README for agents carrying the
build/test commands, the stack, the environment contract, and the boundaries.
Where ``.agent/spec.md`` is scaffold-owned and rewritten every generation,
``AGENTS.md`` is **user-owned once it exists**: the writer creates it when
absent and leaves an existing file untouched (the user may have tuned it),
so regeneration never clobbers instructions a team relies on.

Rendered, not model-generated — every fact here is known post-resolve, so the
render is deterministic and free. Best-effort like the run-summary/spec
writers: a filesystem failure surfaces as a warning, never sinks a run.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from agent_scaffold.capabilities import ResolvedStack
from agent_scaffold.contract import GenerationResult
from agent_scaffold.discovery import Recipe

AGENTS_FILENAME = "AGENTS.md"


def agents_md_path(project_dir: Path) -> Path:
    return project_dir / AGENTS_FILENAME


# Per-tool invocations. A generic "{tool} check ." template rendered commands
# that don't exist (`prettier check .` — prettier wants `--check`; `tsc .` —
# tsc rejects a directory argument), and AGENTS.md is user-owned once written,
# so a broken command would persist across regenerations. Unknown tools fall
# back to their bare name rather than a guessed flag.
_TEST_INVOCATIONS = {"vitest": "vitest run"}
_CHECK_INVOCATIONS = {"ruff": "ruff check .", "prettier": "prettier --check ."}
_TYPECHECK_INVOCATIONS = {"mypy": "mypy .", "tsc": "tsc --noEmit"}


def _commands_section(language: str, hints: dict[str, Any], smoke_check: str) -> list[str]:
    """The toolchain commands, derived from the language hints."""
    package_manager = str(hints.get("package_manager", ""))
    tools = hints.get("required_tools")
    tools = tools if isinstance(tools, dict) else {}
    runner = "uv run" if language == "python" else "pnpm exec"
    install = {"uv": "uv sync", "pnpm": "pnpm install"}.get(package_manager, "")

    rows: list[tuple[str, str]] = []
    if install:
        rows.append(("Install", f"`{install}`"))
    if tools.get("test"):
        tool = str(tools["test"])
        rows.append(("Test", f"`{runner} {_TEST_INVOCATIONS.get(tool, tool)}`"))
    if tools.get("formatter"):
        tool = str(tools["formatter"])
        rows.append(("Lint / format", f"`{runner} {_CHECK_INVOCATIONS.get(tool, tool)}`"))
    if tools.get("type_checker"):
        tool = str(tools["type_checker"])
        rows.append(("Type check", f"`{runner} {_TYPECHECK_INVOCATIONS.get(tool, tool)}`"))
    if smoke_check:
        rows.append(("Smoke", f"`{smoke_check}`"))

    if not rows:
        return []
    lines = ["", "## Commands", ""]
    lines.extend(f"- {label}: {cmd}" for label, cmd in rows)
    return lines


def _services_section(resolved_stack: ResolvedStack | None) -> list[str]:
    if resolved_stack is None:
        return []
    services = [fragment.service for fragment in resolved_stack.docker_services()]
    if not services:
        return []
    lines = [
        "",
        "## Services",
        "",
        "Compose services this project runs (`agent-scaffold up` / `docker compose up`):",
        "",
    ]
    lines.extend(f"- `{svc}`" for svc in services)
    return lines


def _environment_section(recipe: Recipe, resolved_stack: ResolvedStack | None) -> list[str]:
    """Env var names only — the contract, never values."""
    names: list[str] = []
    seen: set[str] = set()

    def _add(var: str) -> None:
        if var and var not in seen:
            seen.add(var)
            names.append(var)

    if resolved_stack is not None:
        for var in resolved_stack.env_vars():
            _add(var)
    for svc in recipe.external_services:
        for var in svc.env_vars:
            _add(var)

    if not names:
        return []
    lines = [
        "",
        "## Environment",
        "",
        "Variables this project reads (names only — values live in `.env.local`, never in git):",
        "",
    ]
    lines.extend(f"- `{name}`" for name in names)
    return lines


def render_agents_md(
    *,
    recipe: Recipe,
    language: str,
    framework: str,
    hints: dict[str, Any],
    result: GenerationResult,
    resolved_stack: ResolvedStack | None,
    agent_role: str | None = None,
) -> str:
    """Render AGENTS.md from the resolved generation inputs (pure)."""
    intro = recipe.title or recipe.slug
    lines: list[str] = [
        f"# {result.project_name}",
        "",
        f"An AI agent generated by agent-scaffold from the `{recipe.slug}` recipe "
        f"({intro}). Target: {language}"
        + (f" / {framework}." if framework and framework != "none" else "."),
    ]
    if agent_role:
        lines += ["", f"Role: {agent_role.strip()}"]

    lines += _commands_section(language, hints, result.smoke_check)
    lines += _services_section(resolved_stack)
    lines += _environment_section(recipe, resolved_stack)

    lines += [
        "",
        "## Boundaries",
        "",
        "- `.agent/spec.md` is scaffold-owned: the resolved spec, rewritten on "
        "regeneration. Read it as the source of truth; do not edit it.",
        "- `.agent/runs/` and `.agent/trace.jsonl` are runtime output — gitignored, "
        "never committed.",
        "- Secrets live in `.env.local` (gitignored). Never write a credential "
        "into a tracked file.",
        "- Do not hand-edit generated lockfiles; change the manifest and re-lock "
        "with the package manager.",
        "- The smoke command above must stay green; treat it as the minimal "
        "acceptance gate for any change.",
        "- The compose services run hardened (no-new-privileges, dropped "
        "capabilities, loopback-bound ports), but a container limits accidents, "
        "not attackers — do not treat it as a security boundary for untrusted "
        "input.",
    ]
    return "\n".join(lines) + "\n"


def write_agents_md(
    project_dir: Path,
    *,
    recipe: Recipe,
    language: str,
    framework: str,
    hints: dict[str, Any],
    result: GenerationResult,
    resolved_stack: ResolvedStack | None,
    agent_role: str | None = None,
) -> Path | None:
    """Write AGENTS.md when absent; return the path, or ``None`` if preserved.

    An existing file is user-owned — regeneration never overwrites it (unlike
    ``.agent/spec.md``, which is a scaffold-owned output). May raise
    ``OSError``; the caller treats that as a warning.
    """
    path = agents_md_path(project_dir)
    if path.exists():
        return None
    text = render_agents_md(
        recipe=recipe,
        language=language,
        framework=framework,
        hints=hints,
        result=result,
        resolved_stack=resolved_stack,
        agent_role=agent_role,
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path


__all__ = [
    "AGENTS_FILENAME",
    "agents_md_path",
    "render_agents_md",
    "write_agents_md",
]
