"""Per-project metadata at ``<project>/.scaffold/manifest.json``.

Written during ``agent-scaffold new`` so ``regenerate`` and ``update`` can
answer "what recipe / language / framework / model generated this project?"
without re-prompting the user.

Schema is versioned (``schema_version``) so future migrations detect older
formats and either upgrade or reject them. Migrations are registered in
:data:`MIGRATIONS` and run in :func:`read_manifest`.

Schema history:

- ``v1`` — initial: recipe, language, framework, topology, roles, model,
  generated_at, files.
- ``v2`` — Q8: adds ``template_snapshot_sha``, ``answers``, and
  ``update_history`` so ``agent-scaffold update`` can do 3-way merges.
"""

from __future__ import annotations

import hashlib
import json
from collections.abc import Callable
from pathlib import Path
from typing import Any

from pydantic import BaseModel, Field

MANIFEST_DIR = ".scaffold"
MANIFEST_FILENAME = "manifest.json"
SCHEMA_VERSION = 2


class ManifestFile(BaseModel):
    path: str
    lines: int
    sha256: str


class UpdateEntry(BaseModel):
    """One row in ``manifest.update_history`` — written per successful ``update``."""

    timestamp: str
    from_schema: int
    to_schema: int
    from_template_sha: str | None = None
    to_template_sha: str
    model: str
    files_added: list[str] = Field(default_factory=list)
    files_modified: list[str] = Field(default_factory=list)
    files_removed: list[str] = Field(default_factory=list)
    files_conflicted: list[str] = Field(default_factory=list)


class Manifest(BaseModel):
    schema_version: int = SCHEMA_VERSION
    recipe: str
    language: str
    framework: str
    topology: str | None = None
    roles: list[dict[str, Any]] = Field(default_factory=list)
    model: str
    generated_at: str
    files: list[ManifestFile] = Field(default_factory=list)
    # ---- v2 additions (Q8 — template evolution) ----
    template_snapshot_sha: str | None = None
    """sha256 of the bundled deployments tree at last successful generation."""
    answers: dict[str, str] = Field(default_factory=dict)
    """Captured prompt answers (recipe slug, language, framework, project name, ...)."""
    update_history: list[UpdateEntry] = Field(default_factory=list)
    """Append-only log of every ``agent-scaffold update`` run that landed."""


class ManifestNotFoundError(Exception):
    """Raised when the project directory has no ``.scaffold/manifest.json``."""


def manifest_path(project_dir: Path) -> Path:
    return project_dir / MANIFEST_DIR / MANIFEST_FILENAME


def hash_file(path: Path) -> tuple[int, str]:
    """Return ``(line_count, hex_sha256)`` for a file on disk."""
    data = path.read_bytes()
    digest = hashlib.sha256(data).hexdigest()
    # Match Python's universal newline counting: count "\n" then add one for
    # the trailing line if the file doesn't end with one.
    text = data.decode("utf-8", errors="replace")
    line_count = text.count("\n") + (0 if text == "" or text.endswith("\n") else 1)
    return line_count, digest


def write_manifest(project_dir: Path, manifest: Manifest) -> Path:
    target = manifest_path(project_dir)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        json.dumps(manifest.model_dump(mode="json"), indent=2, sort_keys=False) + "\n",
        encoding="utf-8",
    )
    return target


# ---------------------------------------------------------------------------
# Schema migrations
# ---------------------------------------------------------------------------


def _v1_to_v2(data: dict[str, Any]) -> dict[str, Any]:
    """Add Q8 fields with safe defaults. Non-destructive."""
    data = dict(data)
    data.setdefault("template_snapshot_sha", None)
    data.setdefault("answers", {})
    data.setdefault("update_history", [])
    data["schema_version"] = 2
    return data


MIGRATIONS: dict[int, Callable[[dict[str, Any]], dict[str, Any]]] = {
    1: _v1_to_v2,
}


def _apply_migrations(data: dict[str, Any]) -> dict[str, Any]:
    current = int(data.get("schema_version", 1))
    while current < SCHEMA_VERSION:
        migrate = MIGRATIONS.get(current)
        if migrate is None:
            raise ManifestNotFoundError(
                f"No manifest migration registered from schema_version {current} -> "
                f"{SCHEMA_VERSION}"
            )
        data = migrate(data)
        current = int(data.get("schema_version", current + 1))
    return data


def read_manifest(project_dir: Path) -> Manifest:
    """Load and (if needed) migrate the manifest from disk."""
    target = manifest_path(project_dir)
    if not target.is_file():
        raise ManifestNotFoundError(
            f"No manifest at {target}. Was this project generated by an older "
            "agent-scaffold? Re-run with `agent-scaffold new` to create one."
        )
    try:
        data = json.loads(target.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ManifestNotFoundError(f"Manifest at {target} is not valid JSON: {exc}") from exc
    migrated = _apply_migrations(data)
    manifest = Manifest.model_validate(migrated)
    # If the migration changed anything, persist it so future reads don't
    # have to redo the work and the user can inspect the upgraded shape.
    if migrated != data:
        write_manifest(project_dir, manifest)
    return manifest


def build_file_entries(project_dir: Path, relative_paths: list[str]) -> list[ManifestFile]:
    """Hash each path under ``project_dir`` and return the manifest file entries."""
    entries: list[ManifestFile] = []
    for rel in relative_paths:
        target = project_dir / rel
        if not target.is_file():
            continue
        lines, digest = hash_file(target)
        entries.append(ManifestFile(path=rel, lines=lines, sha256=digest))
    return entries


def update_file_entry(manifest: Manifest, project_dir: Path, rel_path: str) -> Manifest:
    """Recompute the sha + lines for ``rel_path`` and return an updated manifest copy."""
    target = project_dir / rel_path
    if not target.is_file():
        # Drop the entry if the file is gone.
        kept = [f for f in manifest.files if f.path != rel_path]
        return manifest.model_copy(update={"files": kept})
    lines, digest = hash_file(target)
    new_entry = ManifestFile(path=rel_path, lines=lines, sha256=digest)
    replaced = False
    new_files: list[ManifestFile] = []
    for entry in manifest.files:
        if entry.path == rel_path:
            new_files.append(new_entry)
            replaced = True
        else:
            new_files.append(entry)
    if not replaced:
        new_files.append(new_entry)
    return manifest.model_copy(update={"files": new_files})
