"""Per-project metadata at ``<project>/.scaffold/manifest.json``.

Written during ``agent-scaffold new`` so ``regenerate`` can answer:
"What recipe, language, framework, and model generated this project?"
without re-prompting the user.

Schema is versioned (``schema_version``) so future migrations can detect
older formats and either upgrade or reject them.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

from pydantic import BaseModel, Field

MANIFEST_DIR = ".scaffold"
MANIFEST_FILENAME = "manifest.json"
SCHEMA_VERSION = 1


class ManifestFile(BaseModel):
    path: str
    lines: int
    sha256: str


class Manifest(BaseModel):
    schema_version: int = SCHEMA_VERSION
    recipe: str
    language: str
    framework: str
    topology: str | None = None
    roles: list[dict[str, Any]] = Field(default_factory=list)
    model: str
    generated_at: str
    files: list[ManifestFile] = Field(default_factory=list)


class ManifestNotFoundError(Exception):
    """Raised when the project directory has no ``.scaffold/manifest.json``."""


def manifest_path(project_dir: Path) -> Path:
    return project_dir / MANIFEST_DIR / MANIFEST_FILENAME


def hash_file(path: Path) -> tuple[int, str]:
    """Return ``(line_count, hex_sha256)`` for a file on disk."""
    data = path.read_bytes()
    digest = hashlib.sha256(data).hexdigest()
    # Match Python's universal newline counting: count "\n" then add one for
    # the trailing line if the file doesn't end with one.
    text = data.decode("utf-8", errors="replace")
    line_count = text.count("\n") + (0 if text == "" or text.endswith("\n") else 1)
    return line_count, digest


def write_manifest(project_dir: Path, manifest: Manifest) -> Path:
    target = manifest_path(project_dir)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        json.dumps(manifest.model_dump(mode="json"), indent=2, sort_keys=False) + "\n",
        encoding="utf-8",
    )
    return target


def read_manifest(project_dir: Path) -> Manifest:
    target = manifest_path(project_dir)
    if not target.is_file():
        raise ManifestNotFoundError(
            f"No manifest at {target}. Was this project generated by an older "
            "agent-scaffold? Re-run with `agent-scaffold new` to create one."
        )
    try:
        data = json.loads(target.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ManifestNotFoundError(f"Manifest at {target} is not valid JSON: {exc}") from exc
    return Manifest.model_validate(data)


def build_file_entries(project_dir: Path, relative_paths: list[str]) -> list[ManifestFile]:
    """Hash each path under ``project_dir`` and return the manifest file entries."""
    entries: list[ManifestFile] = []
    for rel in relative_paths:
        target = project_dir / rel
        if not target.is_file():
            continue
        lines, digest = hash_file(target)
        entries.append(ManifestFile(path=rel, lines=lines, sha256=digest))
    return entries


def update_file_entry(manifest: Manifest, project_dir: Path, rel_path: str) -> Manifest:
    """Recompute the sha + lines for ``rel_path`` and return an updated manifest copy."""
    target = project_dir / rel_path
    if not target.is_file():
        # Drop the entry if the file is gone.
        kept = [f for f in manifest.files if f.path != rel_path]
        return manifest.model_copy(update={"files": kept})
    lines, digest = hash_file(target)
    new_entry = ManifestFile(path=rel_path, lines=lines, sha256=digest)
    replaced = False
    new_files: list[ManifestFile] = []
    for entry in manifest.files:
        if entry.path == rel_path:
            new_files.append(new_entry)
            replaced = True
        else:
            new_files.append(entry)
    if not replaced:
        new_files.append(new_entry)
    return manifest.model_copy(update={"files": new_files})
