"""Write ``.agent/spec.md`` — the resolved spec the generated project realizes.

Where ``.scaffold/run-summary.md`` records *what happened* in a generation run,
this file records *what the project is*: the recipe, agent pattern, topology,
resolved capability stack, the agent's role, the files it must contain, and its
environment contract.

It is **deterministic** — a pure function of the resolved generation inputs, no
LLM call, no timestamp — so it is safe to commit and regenerating it produces a
clean diff rather than churn. It is meant to be read and version-controlled by
the developer: the living "spec as referee" that anchors future edits and
regenerations.

Best-effort: a filesystem failure is surfaced as a warning by the caller, never
sinks a run (mirrors :mod:`agent_scaffold.run_summary`).
"""

from __future__ import annotations

from pathlib import Path

from agent_scaffold._scaffold_dir import AGENT_DIR
from agent_scaffold.capabilities import ResolvedStack
from agent_scaffold.contract import GenerationResult
from agent_scaffold.discovery import Recipe

SPEC_FILENAME = "spec.md"


def spec_path(project_dir: Path) -> Path:
    return project_dir / AGENT_DIR / SPEC_FILENAME


def render_spec(
    *,
    recipe: Recipe,
    language: str,
    framework: str,
    model: str,
    result: GenerationResult,
    resolved_stack: ResolvedStack | None,
    template_sha: str | None = None,
) -> str:
    """Render the spec markdown from the resolved generation inputs (pure)."""
    lines: list[str] = [
        f"# Agent spec — {result.project_name}",
        "",
        "The resolved specification this project realizes. Generated by "
        "agent-scaffold; safe to edit and version-control — it is the living "
        "spec future regenerations reconcile against.",
        "",
        "## Recipe",
        "",
        f"- Recipe: `{recipe.slug}`" + (f" — {recipe.title}" if recipe.title else ""),
    ]
    if recipe.status:
        lines.append(f"- Status: {recipe.status}")
    if recipe.agent_pattern:
        lines.append(f"- Pattern: `{recipe.agent_pattern}`")
    if recipe.topology:
        lines.append(f"- Topology: `{recipe.topology}`")
    if template_sha:
        lines.append(f"- Deployments snapshot: `{template_sha[:16]}`")

    lines += [
        "",
        "## Target",
        "",
        f"- Language / framework: {language} / {framework or '(none)'}",
        f"- Model: `{model}`",
    ]

    if recipe.agent_role:
        lines += ["", "## Role", "", recipe.agent_role.strip()]

    lines += _capabilities_section(resolved_stack)
    lines += _required_files_section(recipe)
    lines += _environment_section(recipe, resolved_stack)
    return "\n".join(lines) + "\n"


def write_spec_artifact(
    project_dir: Path,
    *,
    recipe: Recipe,
    language: str,
    framework: str,
    model: str,
    result: GenerationResult,
    resolved_stack: ResolvedStack | None,
    template_sha: str | None = None,
) -> Path:
    """Render and write ``.agent/spec.md``; return the path.

    May raise ``OSError`` on a filesystem failure — the caller treats that as a
    warning, not a run failure (mirrors :func:`run_summary.write_run_summary`).
    """
    text = render_spec(
        recipe=recipe,
        language=language,
        framework=framework,
        model=model,
        result=result,
        resolved_stack=resolved_stack,
        template_sha=template_sha,
    )
    path = spec_path(project_dir)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path


def _capabilities_section(resolved_stack: ResolvedStack | None) -> list[str]:
    lines = ["", "## Capabilities", ""]
    if resolved_stack is None or not resolved_stack.capabilities:
        lines.append("- (none)")
        return lines
    lines.extend(f"- `{cap.id}` ({cap.kind})" for cap in resolved_stack.capabilities)
    if resolved_stack.unresolved:
        lines += [
            "",
            "Declared but not in the catalog (upgrade your deployments source):",
        ]
        lines.extend(f"- `{cid}`" for cid in resolved_stack.unresolved)
    return lines


def _required_files_section(recipe: Recipe) -> list[str]:
    if not recipe.required_files:
        return []
    lines = ["", "## Required files", ""]
    lines.extend(f"- `{rel}`" for rel in recipe.required_files)
    return lines


def _environment_section(recipe: Recipe, resolved_stack: ResolvedStack | None) -> list[str]:
    """Env var NAMES the agent expects — the contract, not the run-time status.

    Union of the resolved capabilities' ``env_vars`` and any the recipe's
    external services declare, deduped in first-seen order. Values never appear.
    """
    names: list[str] = []
    seen: set[str] = set()

    def _add(var: str) -> None:
        if var and var not in seen:
            seen.add(var)
            names.append(var)

    if resolved_stack is not None:
        for var in resolved_stack.env_vars():
            _add(var)
    for svc in recipe.external_services:
        for var in svc.env_vars:
            _add(var)

    if not names:
        return []
    lines = [
        "",
        "## Environment",
        "",
        "Variables this agent expects (names only — set them in your shell or `.env.local`):",
        "",
    ]
    lines.extend(f"- `{name}`" for name in names)
    return lines


__all__ = [
    "SPEC_FILENAME",
    "render_spec",
    "spec_path",
    "write_spec_artifact",
]
